import os
from config import MYCOCOSM_FUNGI_URL, PORTALS_TABLE_PATH, DATA_DIR
from utils.web_utils import download_mycocosm_fungi_table

download_mycocosm_fungi_table(MYCOCOSM_FUNGI_URL, PORTALS_TABLE_PATH)